---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-lab-wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-lab-wordpress
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-lab-wordpress
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: mysql-secrets
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: wordpress
        ports:
        - containerPort: 80
          name: wordpress-port
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-volume
      volumes:
      - name: wordpress-volume
        persistentVolumeClaim:
          claimName: wordpress-volume
